apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: cafe-virtual-server
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.1.10.84"
  host: cafe.de1chk1nd.de
  pools:
  - path: /coffee
    service: coffee-svc
    servicePort: 8080
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
  - path: /tea
    service: tea-svc
    servicePort: 8080
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10