apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-hello-world-web1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f5-hello-world-web1
  template:
    metadata:
      labels:
        app: f5-hello-world-web1
    spec:
      containers:
      - env:
        - name: service_name
          value: f5-hello-world-web1
        image: f5devcentral/f5-hello-world:latest
        imagePullPolicy: Always
        name: f5-hello-world-web1
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: f5-hello-world-web1
  namespace: default
  labels:
    app: f5-hello-world-web1
    cis.f5.com/as3-tenant: AS3_1
    cis.f5.com/as3-app: A1
    cis.f5.com/as3-pool: web_pool1
spec:
  ports:
  - name: f5-hello-world-web1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: f5-hello-world-web1
