kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration1
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "AS3_1": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.1.10.83"
                        ],
                        "pool": "web_pool1"
                    },
                    "web_pool1": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
